// Auto-generated Data File for Sapna Furniture
// Do not edit this file manually if you use the Admin Panel.

const defaultCategories = [
    {
        "id": "wood",
        "name": "Wood Furniture",
        "icon": "fa-tree",
        "color": "#ff7b54",
        "image": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800"
    },
    {
        "id": "office",
        "name": "Office Setup",
        "icon": "fa-desktop",
        "color": "#3b82f6",
        "image": "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800"
    },
    {
        "id": "plastic",
        "name": "Trendy Plastic",
        "icon": "fa-chair",
        "color": "#10b981",
        "image": "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=800"
    },
    {
        "id": "kids",
        "name": "Kids Zone",
        "icon": "fa-baby",
        "color": "#ec4899",
        "image": "https://images.unsplash.com/photo-1585827797745-f0fec2f9bed7?auto=format&fit=crop&w=800"
    },
    {
        "id": "mattress",
        "name": "Sleep & Comfort",
        "icon": "fa-bed",
        "color": "#8b5cf6",
        "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800"
    }
];

const defaultSubcategories = [
    {
        "id": "wood_beds",
        "parentId": "wood",
        "name": "Luxury Beds",
        "image": "https://images.unsplash.com/photo-1505693314120-0d443867891c?w=400"
    },
    {
        "id": "wood_sofas",
        "parentId": "wood",
        "name": "Comfy Sofas",
        "image": "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=400"
    },
    {
        "id": "wood_almaris",
        "parentId": "wood",
        "name": "Storage Wardrobes",
        "image": "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=400"
    },
    {
        "id": "office_tables",
        "parentId": "office",
        "name": "Work Desks",
        "image": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400"
    },
    {
        "id": "office_chairs",
        "parentId": "office",
        "name": "Ergo Chairs",
        "image": "https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?w=400"
    },
    {
        "id": "plastic_chairs",
        "parentId": "plastic",
        "name": "Vibrant Chairs",
        "image": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400"
    },
    {
        "id": "plastic_tables",
        "parentId": "plastic",
        "name": "Outdoor Tables",
        "image": "https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=400"
    },
    {
        "id": "kids_tables",
        "parentId": "kids",
        "name": "Study Tables",
        "image": "https://images.unsplash.com/photo-1602028684725-b44e057134aa?w=400"
    },
    {
        "id": "kids_chairs",
        "parentId": "kids",
        "name": "Mini Chairs",
        "image": "https://images.unsplash.com/photo-1519689680058-324335c77eba?w=400"
    },
    {
        "id": "mattress_five_star",
        "parentId": "mattress",
        "name": "Five Star Diamond",
        "image": "https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=400"
    },
    {
        "id": "mattress_uni_foam",
        "parentId": "mattress",
        "name": "Uni Foam",
        "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400"
    }
];

const defaultProducts = [
    {
        "id": 1,
        "name": "Regal Walnut Double Bed",
        "category": "wood",
        "subcategory": "wood_beds",
        "price": "Rs. 65,000",
        "image": "https://images.unsplash.com/photo-1505693314120-0d443867891c?auto=format&fit=crop&w=800"
    },
    {
        "id": 2,
        "name": "Modern Dressing Table",
        "category": "wood",
        "subcategory": "wood_beds",
        "price": "Rs. 35,000",
        "image": "https://images.unsplash.com/photo-1595514535316-8a0327f31cfa?auto=format&fit=crop&w=800"
    },
    {
        "id": 3,
        "name": "Smart Ironing Stand",
        "category": "wood",
        "subcategory": "wood_almaris",
        "price": "Rs. 4,500",
        "image": "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=800"
    },
    {
        "id": 4,
        "name": "Cloud 7-Seater Sofa",
        "category": "wood",
        "subcategory": "wood_sofas",
        "price": "Rs. 120,000",
        "image": "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=800"
    },
    {
        "id": 5,
        "name": "Glass Crockery Cabinet",
        "category": "wood",
        "subcategory": "wood_almaris",
        "price": "Rs. 45,000",
        "image": "https://plus.unsplash.com/premium_photo-1661766023249-ae1e2edba2e6?auto=format&fit=crop&w=800"
    },
    {
        "id": 7,
        "name": "Tech Pro Executive Desk",
        "category": "office",
        "subcategory": "office_tables",
        "price": "Rs. 25,000",
        "image": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800"
    },
    {
        "id": 8,
        "name": "Posture+ Mesh Chair",
        "category": "office",
        "subcategory": "office_chairs",
        "price": "Rs. 18,000",
        "image": "https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?auto=format&fit=crop&w=800"
    },
    {
        "id": 10,
        "name": "Pop Color Lounge Chair",
        "category": "plastic",
        "subcategory": "plastic_chairs",
        "price": "Rs. 2,200",
        "image": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800"
    },
    {
        "id": 11,
        "name": "All-Weather Patio Table",
        "category": "plastic",
        "subcategory": "plastic_tables",
        "price": "Rs. 5,000",
        "image": "https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?auto=format&fit=crop&w=800"
    },
    {
        "id": 12,
        "name": "Safety First Feeding Chair",
        "category": "kids",
        "subcategory": "kids_chairs",
        "price": "Rs. 3,500",
        "image": "https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=800"
    },
    {
        "id": 14,
        "name": "Five Star Diamond Ortho",
        "category": "mattress",
        "subcategory": "mattress_five_star",
        "price": "Rs. 35,000",
        "image": "https://images.unsplash.com/photo-1631679706909-1844bbd07221?auto=format&fit=crop&w=800"
    },
    {
        "id": 15,
        "name": "Uni Foam Cloud Edition",
        "category": "mattress",
        "subcategory": "mattress_uni_foam",
        "price": "Rs. 28,000",
        "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800"
    }
];

const savedCeoImgData = null;
const savedOwnerImgData = null;
